### ISSUE TITLE
Missing layer form dependency

### ISSUE THREAD

**Issue by mvaaltola** [GispoCoding/qaava#15]
Removing the kuvaustyyli table causes errors with the QGIS project, despite there not being any references to it in layers or relations.

```
WARNING   Missing layer form dependency : layer 'Yleiskaava' requires layer 'Kuvaustyyli' to be loaded but 'Kuvaustyyli' could not be found, please load it manually if possible.
```

Opening the project in .qgs format shows references to the kuvaustyyli exist. Possibly related to https://github.com/qgis/QGIS/issues/39025

**Comment by SannaJokela** [comment]
This is fixed and working now for yleiskaava QGIS project - I will update it soon to dev-database and then it can be taken to production.
