### ISSUE TITLE
Store DB migrations for schema models

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/qaava#2]
Use some kind of DB migration tool (such as [flyway](https://flywaydb.org/)) to create migrations for schema models whenever changes occur. Plugin could then run the migrations to promote existing databases to newest versions. Ping @tjukanovt @lehtojaa.

**Comment by Joonalai** [comment]
@mvaaltola the version information should be stored in some metadata table and the new migration files and information about the versions should be stored in the repository.

**Comment by Joonalai** [comment]
Look [this](https://github.com/mapbox/tilejson-spec) as an example.

yleiskaavan-tietomalli
* 1.0.0
  * yleiskaavan-tietomalli.sql 
* 1.0.1
  * yleiskaavan-tietomalli.sql 
  * migraatio.sql
* versions.txt

versions.txt:
```
1.0.0
1.0.1
```

**Comment by Joonalai** [comment]
Should versioning be used also with kuvaustekniikka etc.?

**Comment by SannaJokela** [comment]
Versioning would be good for the kuvaustekniikka, but I think they are quite static for now at least.
