### ISSUE TITLE
Editing nodes fails at second try

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava#32]
Tested with yleiskaava QGIS profile: 

Add a polygon/line, change nodes and try to change again ==> is not able to change the nodes.

Noticed also by testers. 

Error message: WARNING    Attribuutti-indeksi 4 rajojen [0;0] ulkopuolella

Is this due to topological settings?

**Comment by pavetsu14** [comment]
@SannaJokela Might not be fixable through QGIS. Could be related to this https://gis.stackexchange.com/questions/266458/python-scripting-in-qgis-attribute-index-out-of-bounds-00 ?

**Comment by SannaJokela** [comment]
No longer updated
