### ISSUE TITLE
Adding new rows to tables fails

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/qaava#40]
Observed while fixing issue #31 .

Concerns following tables:
yleiskaava.many_yleiskaava_has_many_kaavamaarays
yleiskaava.many_maankayttoalue_has_many_kaavamaarays
yleiskaava.many_kaavaelementti_has_many_kaavamaarays
kaavan_lisatiedot.many_dokumentti_has_many_yleiskaava
yleiskaava.many_kaavaelementti_has_many_numeerinen_lisatieto
yleiskaava.many_kaavaelementti_has_many_teema
yleiskaava.many_maankayttoalue_has_many_numeerinen_lisatieto
yleiskaava.many_maankayttoalue_has_many_teema
yleiskaava.many_yleiskaava_has_many_teema

The error message:
CRITICAL Layer many_yleiskaava_has_many_kaavamaarays : PostGIS error while adding features: ERROR: null value in column "uuid_yleiskaava" violates not-null constraint
DETAIL: Failing row contains (null, null).

**Comment by SannaJokela** [comment]
no longer updated
